import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import sharp from 'sharp';
import { buildSpriteSheetPrompt } from '@/lib/boxStyles';
import type { DrawerStyle } from '@/lib/types';

// Vision API + Sharp chroma key is much faster than ML bg removal
export const maxDuration = 60;

interface GenerateBoxRequest {
  style: DrawerStyle;
}

export async function POST(request: NextRequest) {
  let builtPrompt: string | undefined;

  try {
    const body: GenerateBoxRequest = await request.json();
    const { style } = body;

    builtPrompt = buildSpriteSheetPrompt(style);

    const apiKey = process.env.GOOGLE_AI_STUDIO_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: 'GOOGLE_AI_STUDIO_KEY not configured', prompt: builtPrompt },
        { status: 500 }
      );
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({
      model: 'gemini-3.1-flash-image-preview',
      // @ts-expect-error - responseModalities not yet in types but supported by API
      generationConfig: { responseModalities: ['Text', 'Image'] },
    });

    // Single prompt for all 5 states as a sprite sheet
    const result = await model.generateContent([{ text: builtPrompt }]);
    const response = result.response;

    // Extract image from response
    let imageBase64: string | null = null;
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const contentParts = candidates[0].content?.parts ?? [];
      for (const part of contentParts) {
        if ((part as any).inlineData) {
          imageBase64 = (part as any).inlineData.data;
          break;
        }
      }
    }

    if (!imageBase64) {
      return NextResponse.json(
        { error: 'No image generated by Gemini', prompt: builtPrompt },
        { status: 500 }
      );
    }

    // Remove green background from the sprite sheet
    let spriteBuffer: Buffer = Buffer.from(imageBase64, 'base64');
    const metadata = await sharp(spriteBuffer).metadata();
    let fullWidth = metadata.width || 2500;
    let fullHeight = metadata.height || 500;
    let ratioWarning: string | undefined;

    // Validate sprite ratio — must be ~5*(W/H):1 for 5 frames with W:H per-frame ratio
    const drawerW = style.drawerWidth || 3;
    const drawerH = style.drawerHeight || 2;
    const expectedRatio = (5 * drawerW) / drawerH;
    const ratio = fullWidth / fullHeight;
    // Allow 30% tolerance before forcing a resize
    if (ratio < expectedRatio * 0.7) {
      const targetWidth = Math.round(fullHeight * expectedRatio);
      ratioWarning = `Gemini returned ${fullWidth}×${fullHeight} (${ratio.toFixed(1)}:1), expected ~${expectedRatio.toFixed(1)}:1, resized to ${targetWidth}×${fullHeight}`;
      spriteBuffer = await sharp(spriteBuffer)
        .resize(targetWidth, fullHeight, { fit: 'contain', background: { r: 0, g: 255, b: 0, alpha: 1 } })
        .toBuffer();
      fullWidth = targetWidth;
    }

    let bgRemoval: 'vision' | 'chroma-fallback';
    let visionObjects = 0;
    let processedBase64: string;

    const visionApiKey = process.env.GOOGLE_CLOUD_VISION_API_KEY;

    if (visionApiKey) {
      // Vision API-assisted chroma key removal
      try {
        const visionRes = await fetch(
          `https://vision.googleapis.com/v1/images:annotate?key=${visionApiKey}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              requests: [{
                image: { content: imageBase64 },
                features: [{ type: 'OBJECT_LOCALIZATION', maxResults: 10 }],
              }],
            }),
          }
        );
        const visionData = await visionRes.json();
        const objects = visionData.responses?.[0]?.localizedObjectAnnotations ?? [];
        visionObjects = objects.length;

        // Build object mask regions from Vision API bounding polys
        const objectRegions = objects.map((obj: any) => {
          const vertices = obj.boundingPoly?.normalizedVertices ?? [];
          return vertices.map((v: any) => ({
            x: Math.round((v.x || 0) * fullWidth),
            y: Math.round((v.y || 0) * fullHeight),
          }));
        });

        processedBase64 = await removeGreenWithVision(spriteBuffer, fullWidth, fullHeight, objectRegions);
        bgRemoval = 'vision';
      } catch (visionErr) {
        console.warn('Vision API failed, falling back to pure chroma key:', visionErr);
        processedBase64 = await removeGreenChromaKey(spriteBuffer);
        bgRemoval = 'chroma-fallback';
      }
    } else {
      // Pure chroma key removal (no Vision API key)
      processedBase64 = await removeGreenChromaKey(spriteBuffer);
      bgRemoval = 'chroma-fallback';
    }

    return NextResponse.json({
      sprite: processedBase64,
      prompt: builtPrompt,
      mimeType: 'image/png',
      spriteSize: { width: fullWidth, height: fullHeight, frameCount: 5 },
      bgRemoval,
      visionObjects,
      ...(ratioWarning && { ratioWarning }),
    });
  } catch (error: any) {
    console.error('Box generation error:', error);
    return NextResponse.json(
      { error: error.message || 'Generation failed', details: String(error), prompt: builtPrompt },
      { status: 500 }
    );
  }
}

/**
 * Remove #00FF00 chroma key green using Vision API object bounds for edge refinement.
 * - Pixels outside object bounds: aggressive green removal (wide tolerance)
 * - Pixels near object edges: feathered alpha for smooth transitions
 * - Pixels inside objects: conservative removal (preserve green-tinted shadows)
 */
async function removeGreenWithVision(
  buffer: Buffer,
  width: number,
  height: number,
  objectRegions: { x: number; y: number }[][],
): Promise<string> {
  const { data, info } = await sharp(buffer)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const pixels = new Uint8Array(data.buffer, data.byteOffset, data.length);

  // Build a distance map from object edges (simplified: use bounding boxes)
  const edgeDistance = buildEdgeDistanceMap(width, height, objectRegions);

  for (let i = 0; i < pixels.length; i += 4) {
    const r = pixels[i];
    const g = pixels[i + 1];
    const b = pixels[i + 2];

    const pixelIdx = i / 4;
    const dist = edgeDistance[pixelIdx];

    // Green detection — wider tolerance for Gemini's varied greens
    const greenDominance = g - Math.max(r, b);
    const isGreen = greenDominance > 50 && g > 150;
    const isSoftGreen = greenDominance > 20 && g > 120;

    if (isGreen) {
      // Strong green — always remove
      pixels[i + 3] = 0;
    } else if (isSoftGreen && dist > 3) {
      // Soft green outside object bounds — remove
      pixels[i + 3] = 0;
    } else if (isSoftGreen && dist > 0) {
      // Soft green near object edge — feather alpha
      const alpha = Math.round((1 - dist / 4) * 255);
      pixels[i + 3] = Math.min(pixels[i + 3], Math.max(0, alpha));
    }
    // Inside object or not green — keep as-is
  }

  const result = await sharp(Buffer.from(pixels.buffer, pixels.byteOffset, pixels.length), {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .png()
    .toBuffer();

  return result.toString('base64');
}

/**
 * Pure chroma key removal — removes #00FF00 green pixels.
 * No Vision API needed. Works well for flat uniform green backgrounds.
 */
async function removeGreenChromaKey(
  buffer: Buffer,
): Promise<string> {
  const { data, info } = await sharp(buffer)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const pixels = new Uint8Array(data.buffer, data.byteOffset, data.length);

  for (let i = 0; i < pixels.length; i += 4) {
    const r = pixels[i];
    const g = pixels[i + 1];
    const b = pixels[i + 2];

    // Green detection — Gemini produces varied greens, not just #00FF00
    const greenDominance = g - Math.max(r, b);

    if (greenDominance > 50 && g > 150) {
      // Strong green — fully transparent
      pixels[i + 3] = 0;
    } else if (greenDominance > 20 && g > 120) {
      // Soft green (edges, anti-aliasing) — feathered transparency
      const greenness = greenDominance / g;
      const alpha = Math.round((1 - greenness) * 255);
      pixels[i + 3] = Math.min(pixels[i + 3], Math.max(0, alpha));
    }
  }

  const result = await sharp(Buffer.from(pixels.buffer, pixels.byteOffset, pixels.length), {
    raw: { width: info.width, height: info.height, channels: 4 },
  })
    .png()
    .toBuffer();

  return result.toString('base64');
}

/**
 * Build a simplified distance map from object bounding box edges.
 * Returns distance in pixels from nearest object edge for each pixel.
 * Positive = outside object, 0 = on edge, negative values not used.
 */
function buildEdgeDistanceMap(
  width: number,
  height: number,
  objectRegions: { x: number; y: number }[][],
): Float32Array {
  const map = new Float32Array(width * height).fill(999);

  // Convert polygon regions to bounding boxes for efficiency
  for (const region of objectRegions) {
    if (region.length < 2) continue;
    const xs = region.map(p => p.x);
    const ys = region.map(p => p.y);
    const minX = Math.max(0, Math.min(...xs));
    const maxX = Math.min(width - 1, Math.max(...xs));
    const minY = Math.max(0, Math.min(...ys));
    const maxY = Math.min(height - 1, Math.max(...ys));

    // Mark pixels inside bounding box with distance from edge
    for (let y = Math.max(0, minY - 5); y <= Math.min(height - 1, maxY + 5); y++) {
      for (let x = Math.max(0, minX - 5); x <= Math.min(width - 1, maxX + 5); x++) {
        const distToEdge = Math.min(
          Math.abs(x - minX),
          Math.abs(x - maxX),
          Math.abs(y - minY),
          Math.abs(y - maxY),
        );

        const inside = x >= minX && x <= maxX && y >= minY && y <= maxY;
        const dist = inside ? -distToEdge : distToEdge;
        const idx = y * width + x;
        map[idx] = Math.min(map[idx], dist);
      }
    }
  }

  return map;
}
