import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import sharp from 'sharp';
import { buildSpriteSheetPrompt } from '@/lib/boxStyles';
import type { BoxState, DrawerStyle } from '@/lib/types';

// Allow up to 120s — one Gemini call + 5 bg removals
export const maxDuration = 120;

const STATES_IN_ORDER: BoxState[] = ['IDLE', 'HOVER_PEEK', 'OPEN', 'HOVER_CLOSE', 'SLAMMING'];

interface GenerateBoxRequest {
  style: DrawerStyle;
}

export async function POST(request: NextRequest) {
  let builtPrompt: string | undefined;

  try {
    const body: GenerateBoxRequest = await request.json();
    const { style } = body;

    // Build prompt early so it's available in error responses
    builtPrompt = buildSpriteSheetPrompt(style);

    const apiKey = process.env.GOOGLE_AI_STUDIO_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: 'GOOGLE_AI_STUDIO_KEY not configured', prompt: builtPrompt },
        { status: 500 }
      );
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({
      model: 'gemini-2.5-flash-image',
      // @ts-expect-error - responseModalities not yet in types but supported by API
      generationConfig: { responseModalities: ['Text', 'Image'] },
    });

    // Single prompt for all 5 states as a sprite sheet
    const result = await model.generateContent([{ text: builtPrompt }]);
    const response = result.response;

    // Extract image from response
    let imageBase64: string | null = null;
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const contentParts = candidates[0].content?.parts ?? [];
      for (const part of contentParts) {
        if ((part as any).inlineData) {
          imageBase64 = (part as any).inlineData.data;
          break;
        }
      }
    }

    if (!imageBase64) {
      return NextResponse.json(
        { error: 'No image generated by Gemini', prompt: builtPrompt },
        { status: 500 }
      );
    }

    // Split the sprite sheet into 5 frames
    const spriteBuffer = Buffer.from(imageBase64, 'base64');
    const metadata = await sharp(spriteBuffer).metadata();
    const fullWidth = metadata.width || 1024;
    const fullHeight = metadata.height || 512;
    const frameWidth = Math.floor(fullWidth / 5);

    const frames: Record<string, string> = {};
    const bgRemovalStatus: Record<string, string> = {};

    for (let i = 0; i < 5; i++) {
      const state = STATES_IN_ORDER[i];

      // Crop each frame from the sprite sheet
      const frameBuffer = await sharp(spriteBuffer)
        .extract({
          left: i * frameWidth,
          top: 0,
          width: frameWidth,
          height: fullHeight,
        })
        .png()
        .toBuffer();

      // ML-based background removal
      let outputBase64: string;
      try {
        const { removeBackground } = await import('@imgly/background-removal-node');
        const blob = new Blob([new Uint8Array(frameBuffer)], { type: 'image/png' });
        const resultBlob = await removeBackground(blob, {
          model: 'small',
          output: { format: 'image/png' },
        });
        const resultBuffer = Buffer.from(await resultBlob.arrayBuffer());
        outputBase64 = resultBuffer.toString('base64');
        bgRemovalStatus[state] = 'success';
      } catch (bgError) {
        console.warn(`ML bg removal failed for ${state}, using raw frame:`, bgError);
        outputBase64 = frameBuffer.toString('base64');
        bgRemovalStatus[state] = `fallback: ${bgError instanceof Error ? bgError.message : String(bgError)}`;
      }

      frames[state] = outputBase64;
    }

    return NextResponse.json({
      frames,
      prompt: builtPrompt,
      mimeType: 'image/png',
      spriteSize: { width: fullWidth, height: fullHeight, frameWidth },
      bgRemovalStatus,
    });
  } catch (error: any) {
    console.error('Box generation error:', error);
    return NextResponse.json(
      { error: error.message || 'Generation failed', details: String(error), prompt: builtPrompt },
      { status: 500 }
    );
  }
}
